# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Redis Deployment on OCI"
description: "Redis Deployment on OCI"
informationalText: "Press the blue button to navigate to management console"
schemaVersion: 1.1.0
version: "20220210"
locale: "en"

variableGroups:
- title: Login Credentials
  visible: false
  variables:
    - scalegrid_username
    - scalegrid_password

- title: Redis Cluster Configuration
  visible: true
  variables:
    - cluster_name
    - redis_version
    - server_count
    - shard_count
    - size
    - cidr_list
    - machine_pool_list
    - backup_interval

variables:

  cluster_name:
    type: string
    required: true
    title: "Redis Cluster Name"
    description: "Name for Redis Cluster. Only alpha numerics and hyphens(-) are allowed."

  redis_version:
    title: "Redis Version"
    required: true
    type: enum
    description: "Please choose the supported Redis version"
    default: "v6.2.5"
    enum:
      - "v6.2.5"
      - "v6.0.4"
      - "v5.0.5"

  redis_version_map:
    title: "version Mapping"
    visible: false

  server_count:
    type: integer
    required: true
    minimum: 1
    maximum: 5
    multipleOf: 1
    default: 1
    title: "Number of nodes in each shard"
    description: "1 for standalone. For master/slave cluster, if this is an even number, ensure to set the sentinelCount as one higher than this."
  
  shard_count:
    type: integer
    required: true
    minimum: 1
    maximum: 5
    multipleOf: 1
    default: 1
    title: "Number of shards in the cluster."
    description: "1 if clusterMode is false."

  size:
    title: "Size of the cluster"
    required: true
    type: enum
    description: "Please choose the supported size."
    default: "Micro(2 vCPU,2GB RAM, 1/8 baseline)"
    enum:
      - "Micro(2 vCPU,2GB RAM, 1/8 baseline)"
      - "Small(4 vCPU,4GB RAM, 1/2 baseline)"
      - "Medium(2 vCPU,8GB RAM)"
      - "Large(4 vCPU,16GB RAM)"
      - "Xlarge(4 vCPU,30GB RAM)"

  size_map:
    title: "Size Mapping"
    visible: false

  cidr_list:
    type: array
    required: true
    title: "CIDR List"
    items:
      type: string
    default: [ 10.1.0.0/24 ]
    description: "Only these IPs will be allowed access to the deployment"

  machine_pool_list:
    title: "Machine Pool Region"
    required: true
    type: enum
    description: "Region which the cluster will be deployed"
    default: "ap-mumbai-1"
    enum:
      - "ap-mumbai-1"
      - "ap-melbourne-1"
      - "ap-sydney-1"
      - "oci-byoc-mumbai"

  machine_pool_map:
    title: "Machine Pool Region Mapping"
    visible: false

  backup_interval:
    type: integer
    required: true
    minimum: 0
    maximum: 24
    multipleOf: 1
    default: 24
    title: "Backup interval in hour"
    description: "0 if backup if not required"

  scalegrid_username:
    type: string
    required: true
    title: "ScaleGrid Username"
    description: "Username for ScaleGrid"

  scalegrid_password:
    title: "ScaleGrid Password"
    type: password
    required: true
    description: "Password for ScaleGrid"

outputs:
  scalegrid_redis_url:
    type: link
    title: "Management Console"
    displayText: "Management Console"
    visible: true

  cluster_name:
    type: string
    title: "Cluster Name"
    displayText: "Cluster Name"
    visible: true

  size:
    type: string
    title: "Size of the cluster"
    displayText: "Size of the cluster"
    visible: true

  machine_pool_list:
    type: string
    title: "Machine Pool Region"
    displayText: "Machine Pool Region"
    visible: true

primaryOutputButton: ${scalegrid_redis_url}